[package]
name = "rates"
publish = false
version = "0.1.0"
authors = ["yarik <yaroslav.stepanchuk@trdata.com>"]

[dependencies]
exonum = { version = "0.9.0", path = "../../exonum" }
failure = "=0.1.1"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
toml = "0.4.0"

